/**************************CONTACTS***************************/
 export const REQUEST_FETCH_CONTACTS = "REQUEST_FETCH_CONTACTS";
 export const SUCCESS_FETCH_CONTACTS = "SUCCESS_FETCH_CONTACTS";
 export const FAIL_FETCH_CONTACTS = "FAIL_FETCH_CONTACTS";

 export const REQUEST_DELETE_CONTACT = "REQUEST_DELETE_CONTACT";
 export const SUCCESS_DELETE_CONTACT = "SUCCESS_DELETE_CONTACT";
 export const FAIL_DELETE_CONTACT = "FAIL_DELETE_CONTACT";

 export const REQUEST_ADD_CONTACT = "REQUEST_ADD_CONTACT";
 export const SUCCESS_ADD_CONTACT = "SUCCESS_ADD_CONTACT";
 export const FAIL_ADD_CONTACT = "FAIL_ADD_CONTACT";

 export const REQUEST_EDIT_CONTACT = "REQUEST_EDIT_CONTACT";
 export const SUCCESS_EDIT_CONTACT = "SUCCESS_EDIT_CONTACT";
 export const FAIL_EDIT_CONTACT    = "FAIL_EDIT_CONTACT";