/**************************USERS***************************/
export const REQUEST_FETCH_USERS = "REQUEST_FETCH_USERS";
export const SUCCESS_FETCH_USERS = "SUCCESS_FETCH_USERS";
export const FAIL_FETCH_USERS = "FAIL_FETCH_USERS";

export const REQUEST_DELETE_USER = "REQUEST_DELETE_USER";
export const SUCCESS_DELETE_USER = "SUCCESS_DELETE_USER";
export const FAIL_DELETE_USER = "FAIL_DELETE_USER";

export const REQUEST_ADD_USER = "REQUEST_ADD_USER";
export const SUCCESS_ADD_USER = "SUCCESS_ADD_USER";
export const FAIL_ADD_USER = "FAIL_ADD_USER";

export const REQUEST_EDIT_USER = "REQUEST_EDIT_USER";
export const SUCCESS_EDIT_USER = "SUCCESS_EDIT_USER";
export const FAIL_EDIT_USER    = "FAIL_EDIT_USER";

export const REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER";
export const SUCCESS_LOGIN_USER = "SUCCESS_LOGIN_USER";
export const FAIL_LOGIN_USER = "FAIL_LOGIN_USER";

export const REQUEST_LOGOUT_USER = "REQUEST_LOGOUT_USER";
export const SUCCESS_LOGOUT_USER = "SUCCESS_LOGOUT_USER";
export const FAIL_LOGOUT_USER = "FAIL_LOGOUT_USER";


